/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nac.tbot;

import javax.swing.JFrame;
import javax.swing.JPanel;
import nac.tbot.tetrisbattle.TetrisBattleAction;
import nac.tbot.tetrisbattle.TetrisBattleBot;
import nac.tbot.tetrisbattle.TetrisBattleSight;

/**
 *
 * @author user
 */
public class Runner extends javax.swing.JFrame {

  private final Sight sight;
  private final Bot bot;
  private final Action action;

  /**
   * Creates new form Runner
   */
  public Runner() {
    initComponents();
    sight = new TetrisBattleSight();
    bot = new TetrisBattleBot();
    sight.setSightReactor(new SightReactor() {

      @Override
      public void newPiece(int index) {
        bot.newPiece(sight.getBoard(), index);
        tGridPanel1.setBoard(sight.getBoard());
        tGridPanel1.repaint();
      }

    });
    action = new TetrisBattleAction();
    bot.setAction(action);
    jTabbedPane1.addTab("Sight", sight.getOption());
    jTabbedPane1.addTab("Action", action.getOption());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tGridPanel1 = new nac.tbot.tetrisbattle.TGridPanel();
    jTabbedPane1 = new javax.swing.JTabbedPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowFocusListener(new java.awt.event.WindowFocusListener() {
      public void windowGainedFocus(java.awt.event.WindowEvent evt) {
        formWindowGainedFocus(evt);
      }
      public void windowLostFocus(java.awt.event.WindowEvent evt) {
        formWindowLostFocus(evt);
      }
    });

    javax.swing.GroupLayout tGridPanel1Layout = new javax.swing.GroupLayout(tGridPanel1);
    tGridPanel1.setLayout(tGridPanel1Layout);
    tGridPanel1Layout.setHorizontalGroup(
      tGridPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 179, Short.MAX_VALUE)
    );
    tGridPanel1Layout.setVerticalGroup(
      tGridPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 360, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(tGridPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jTabbedPane1)
          .addComponent(tGridPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus

  }//GEN-LAST:event_formWindowLostFocus

  private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

  }//GEN-LAST:event_formWindowGainedFocus

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */

    JFrame.setDefaultLookAndFeelDecorated(true);
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {

        new Runner().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane jTabbedPane1;
  private nac.tbot.tetrisbattle.TGridPanel tGridPanel1;
  // End of variables declaration//GEN-END:variables
}
