/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nac.tbot.tetrisbattle;

/**
 *
 * @author user
 */
public class MeasureFrame extends javax.swing.JFrame {
  
  private final TetrisBattleSight sight;

  /**
   * Creates new form MeasureFrame
   *
   * @param sight
   */
  public MeasureFrame(TetrisBattleSight sight) {
    this.sight = sight;
    initComponents();
    setResizable(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    measurePanel1 = new nac.tbot.tetrisbattle.TGridPanel();

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    javax.swing.GroupLayout measurePanel1Layout = new javax.swing.GroupLayout(measurePanel1);
    measurePanel1.setLayout(measurePanel1Layout);
    measurePanel1Layout.setHorizontalGroup(
      measurePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 179, Short.MAX_VALUE)
    );
    measurePanel1Layout.setVerticalGroup(
      measurePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 360, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(measurePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(measurePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    sight.setLocation(measurePanel1.getLocationOnScreen());
    sight.setActive(true);
  }//GEN-LAST:event_formWindowClosing

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    sight.setActive(false);
  }//GEN-LAST:event_formWindowOpened


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private nac.tbot.tetrisbattle.TGridPanel measurePanel1;
  // End of variables declaration//GEN-END:variables
}
